from platform import uname
from time import sleep

from userbot import ALIVE_NAME, CMD_HELP
from userbot.events import register

# ================= CONSTANT =================
DEFAULTUSER = str(ALIVE_NAME) if ALIVE_NAME else uname().node
# ============================================


@register(outgoing=True, pattern="^.gigolo(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**EH BOCAH TOLOL YANG KERJAAN NYA JADI GIGOLO LEBIH BAIK LU APUS TELE DARI PADA DI TELEGRAM JADI RAJA JAMET MENDING GUE YE KAN RAJA PARA ORANG GANTENG TOLOL**"
    )
    sleep(2)
    await typew.edit(
        "**NI YE EMAK LU KEMARIN TUH DATANG KERUMAH GUE MINTA MEMEK NYA DI INJAK YA UDAH GUE INJAK KERENA MAMA LU SANGE LIAT GUE**"
    )
    sleep(1)
    await typew.edit(
        "**CEWEK LU AJA PAS KETEMU GUE LANGSUNG TELANJANG KERENA GUE TERLALU GANTENG YANG GANTENG NYA KELWATAN**"
    )
    sleep(2)
    await typew.edit(
        "**GA KAYA LU WAJAH BABI YANG GUSI LU AJA UDAH MAU TUMBUH GADING BABI MANA IDUNG LU ITU UDAH KEK BEBEK ANJING**"
    )
    sleep(1)
    await typew.edit(
        "**NI LAGI GUE TAU LU KEMARIN KENA CAKAR KUCING KAN KERENA KUCING NYA NGOMONG KALO LO ITU HINA BANGET DI MATA SI KUCING**"
    )
    sleep(2)
    await typew.edit(
        "**KUCING AJA BILANG LU HINA APA LAGI GUE YE KAN DASAR BOCAH HINA YE KAN KASIAN BANGET**"
    )
    sleep(1)
    await typew.edit(
        "**GUE TAU NIH YE KAN KEMAREN LU NGEMIS DI BUNDARAN H I KERENA LU GA PUNYA UANG BUAT BELI KONDOM**"
    )
    sleep(2)
    await typew.edit(
        "**GUE TAU TU KONDOM BUAT NGENTOD AMA BABI KERENA APA GA ADA CEWEK MAU. DI AJAK LU NGEOTD YA KALI ADA YANG MAU**"
    )
    sleep(1)
    await typew.edit(
        "**CEWEK AJA KALO LIAT LO BAWAAN NYA MAU BUNUH DIRI KERENA HINA NYA WAJH LO DI MATA MEREKA**"
    )


@register(outgoing=True, pattern=r"^\.ovt(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**CIAHH OVERTHINKNG 🤣**")
    sleep(1.5)
    await typew.edit("**DARI PADA OVER THINKING**")
    sleep(1.5)
    await typew.edit("🎵 `mending gua nongki......`")
    sleep(1.5)
    await typew.edit("🎵 `ketempat kopi.......`")
    sleep(1.5)
    await typew.edit("🎵 `nyalain wi-fi......`")
    sleep(1.5)
    await typew.edit("🎵 `stalkingin do'i....`")
    sleep(1.5)
    await typew.edit("🎵 `berharap gua...`")
    sleep(1.5)
    await typew.edit("🎵 `jadi jodohnya....`")
    sleep(1.5)
    await typew.edit("🎵 `aaaaaa....`")
    sleep(1.5)
    await typew.edit("**😰 Bangst gua gabut banget**")
    sleep(1.5)
    await typew.edit("🥱 `berantem yok......`")
    sleep(1.5)
    await typew.edit("😤 `kangen di bacok bacokin nih aing`")
    sleep(1.5)
    await typew.edit("😣 **INI GAADA YANG MAU APA!!**")
    sleep(1.5)
    await typew.edit("😡 **EHH NGENTOT AYU APA ANJ**")


@register(outgoing=True, pattern="^.ngerocos(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit(
        "**EH BOCAH TOLOL YANG JALAN AJA GA PAKEK SENDAL MANA KALO JALAN LETOY KEK JERAMI**"
    )
    sleep(1)
    await typew.edit(
        "**YANG UDAH MAU MATI DIKIT LAGI YANG MAU MASUK NERAKA MENDING SEKARANG LU DZIKIR DARI PADA MATI YE KAN ANJING BANGET EMANG TOLOL HAHAHA**"
    )
    sleep(1)
    await typew.edit(
        "**SUARA UDAH KEK BABI GITU MANA MULUT LU NGEROCOS KEK EMAK EMAK MAU KONDANGAN**"
    )
    sleep(1)
    await typew.edit(
        "**YANG MANA KALO DI KONDANGAN MALAH NUMPANG MAKAN AJA YE KAN KERENA GUE TAU LU GA PERNAH MAKAN MAHAL KASIAN BANGET ANJING**"
    )
    sleep(1)
    await typew.edit(
        "**IYA BAPA LO MAU MATI TOLOO MANGKANYA DIRUMAH GUE TAU BAPA LO SEKARAT KAN TOLOL**"
    )


@register(outgoing=True, pattern="^.kake(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**KAKEK LO DULU ITU JADI BABU BABU KOMPENI YANG DI SURUH BIKININ KOPI TERUS MOTONG RUMPUT DI HALAMAN RUMAH YAELAH KASIAN BAT KASIAN KAKEK LO ITU UDAH KONTET KURUS KERING KEREMPENG LAGI KAKEK LO DULU MATINYA KE ABISAN TENAGA PAS NYABUTIN RUMPUT TOLOL HAHA NENEK LO JUGA JADI LACUR KOMPENI NENEK LO AJE JADI LACUR KOMPENI CUMA DI BAYAR PAKE SINGKONG REBUS DOANG SATU BIJI TERUS NENEK LO ITU MATINYA PAS DI GANGBANG SAMA TENTARA KOMPENI MEMEK NENEK LO ITU DI SODOK SODOK MAKE SENAPAN NOH SAMPE MEMEKNYA LOBEH LEBAR BAT LEBAR KEK JALAN RAYA HAHA**"
    )


@register(outgoing=True, pattern="^.badut(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**EHH TOLOL BADUT BADUT IYE GUE TAU LO MAIN TELE ITU DI JADIIN BADUT ALIANSI KAN HAHAHA MANGKANYA BANG KALO JADI ORANG PAS DI SENGGOL LAWAN JANGAN DIEM BAE KEK BATU HAHA DI JADIIN BADUT KAN LO DI LEDEK LEDEKIN SAMA SEMUA ALIANSI,GUE TAU TUJUAN LO MAEN TELE ITU UNTUK MENCARI MEMEK MEMEK SEGAR KAN HAHA KETAUAN ORANG ORANG KEK LO OTAK SANGEAN YANG HAUS AKAN MEMEK DAN TOKET SAKING GK MAU MODAL DI RL BUAT NYEWA LACUR JADI LO MEMILIH BIAT MAIN TELE BORO BORO DAPET LAH LU KAGA DAPET SAMA SEKALI MANGKANYA GANTENG KONTOL LO UDAH JELEK PENGENNYA YANG BAGUS BAGUS NYADAR DIRI LO ITU UDAH JELEK TERUS MISKIN LAGI**"
    )


@register(outgoing=True, pattern="^.mesum(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**EHH TOLOL BOCAH KAGA ADA BERSYUKUR NYA LO UDAH DI KASIH OTAK SAMA TUHAN LO MALAH KAGA DI PAKE DENGAN BAIK DAN BENAR GUE TAU OTAK LO DI PERGUNAKAN BUAT NGINGET HAL HAL MESUM DOANG KAN HAHAHA YAELAH HINA BAT KEK PEKERJAAN EMAK LO ITU EMAK LO LAN LACUR YANG HARGA DIRINYA SANGAT AMAT RENDAH,LO GANTENG?BHAKS GANTENG BUKAN MENGAKUI MAS GANTENG ITU DI AKUI MUKA LO AJA BENTUKANNYA KEK KARDUS INDOMIE (KOTAK) MIRIP ADUDU LO KEK DI FILM BOBOIBOY ,UDAH PALA KOTAK, MISKIN HARTA MISKIN PENDIDIKAN PULA KAGA PANTES LO IDUP DI DUNIA INI LO IDUP JUGA NYUSAHIN ORANG TUA ANGKAT LO DOANG KASIAN BAT ANAK PUNGUT HAHA BORO BORO DI PUNGGUT SAMA ORANG KAYA LAH ELU DI PUNGGUT SAMA LACUR TERUS BOKAP LO ITU KERAJAAN CUMA NGEJUDI SAMA BETAKIN SEMPAK JANDA HAHA ANAK EMAK BAPAK KELAKUANNYA SAMA AJA SAMA SAMA BEJAT HOBINYA MESUM MULU BOKAP LO NOH KALO UDAH DAPET SEMPAK TETANGGA LANGSUNG NYODOKIN POHON PISANG TOLOL SAMPE ROBOH SAKING SANGENYA HAHAHA MANGKANYA BILANGIN KE BOKAP LO KALO SANGE MODAL JANGAN POHON PISANG LO EMBAT JUGA**"
    )


@register(outgoing=True, pattern="^.petinggi(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**ANGJAS PETINGGINYA NONGOL NIH YHAHAHA EH TOLOL BOKAP LO NOH YANG ALAY UDAH TUA MALAH IKUTAN MAEN TIKTOK DI BEKASI MAKE BAJU KOTAK KOTAK YANG BENTUKANNYA KEK PAPAN CATUR TERUS MAKE CELANA SOBEK YANG KELIATAN DENGKUL NYA BORO BORO DENGGUL BOKAP LO PUTIH LAH INI DENGKUL BOKAP LO AJE BENTUKANNYA KEK UBIN BENGKEL ITEM BAT ITEM MIRIS BAT NGELIAT BOKAP LO YANG UDAH TUA TERUS KURUS KERING KEREMPENG TINGGAL TULANG SAMA KENTUT TIKTOKAN LAGI FYP JUGA KAGA,EH MENDING LO BILANGIN KE BOKAP LO ITU UDAH TUA INGET UMUR TOLOL JANGAN TIKTOKAN TERUS KASIAN NOH ATAP RUMAH LO BOCOR BELOM DI TAMBEL RUMAH LO KAN KALO PAS UJAN BANJIR GEGARA GENTENGNYA BOCOR HAHAA KASIAN BAT KASIAN,EMAK LO NOH KALO TIAP PAGI MULUNG KERJAANNYA TERUS MALEMNYA NGELACUR TAPI KAGA LAKU LAKU KARNA APA?EMAK LO JELEK, EMAK LO ITU BENTUKANNYA KEK TAPIR TOLOL MUKA SAMA PANTAT WARNANYA ITEM GELAP BAT GELAP KEK MASA DEPAN LO ITU**"
    )


@register(outgoing=True, pattern="^.blepotan(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**GUA KASIH TAHU NI BUAT LU YA BOCAH AUTIS YANG TYPING NYA AJA MASIH BELEPOTAN WAJAH GUA AMA WAJAH LU NI YA MASIH CAKEPAN WAJAH GUA TOLOL GUA GA MAU MASANG PP KARNA GUA TAKUT KLO CEWE-CEWE DI TELE PADA SUKA SAMA GUA SOAL NYA APA SOAL GUA GANTENG NYA 7 TURUNAN BEGO GA KAYAK ELU YANG MUKA NYA PANUAN,KORENGAN UDH KAYAK PANTAT PANCI TUH MUKA LU,LU TAHU GA PANTAT PANCI IYAA ITEM DEKIL,KORENGAN LAGI YE KAN JAJMHAHAH ITU KARNA APA KARNA SPERMA BAPAK LU SPERMA GAGAL TOLOL MAKANNYA HASIL NYA BEGITU GADA CAKEP-CAKEP NYA MUKA ANAK NYA UDH KAYAK PANTAT BABI YANG ADA DI MEDAN MUKA LU XIXIXI,TUHH APA LAGI TYPINGAN LU GBLK JELEK NYA MINTA AMPUN PAKE NGEHALU SEGALA BILANGIN BAPAK GUA TUKANG SAPU BAPAK GUA MAH PEKERJA KERAS BEGO GA KAYAK BAPAK LU YANG KESEHARIAN NYA CUMAN MALING,JUDI AMA MABOK-MABOKAN MULU MAKANNYA MUKA BAPAK LU BIRU-BIRU KARNA APA KARNA HABIS DIPUKULI BEGI APA WARGA AKIBAT MALING GAS IBU-IBU YANG LAGI BUNTING DIH DIH DIH NAJIS BENER PUNYA BAPAK KAYAK GITU**"
    )


@register(outgoing=True, pattern="^.kudanil(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**WOI KUDANIL MUKA UDAH BULET KEK CAKIL BOCAH SAGAPUNG GILA PENTIL SINI DONG ITIL REP IN GUA BIAR GA KEK ORANG TOLOL GITU TYPING TIPIS BAT KEK BADAN LU UDAH MANA SISA HIDUPLU SEDIKIT BAT ANAK YANG HARAM KEK LU LAHIR DARI MAK YANG JADI KACUNG DI LUAR NEGRI MANA UDAH JADI JONGOS DICAMBUKIN KARENA GAPERNAH BENER KERJA NYA PEN BAT YA GAJI GEDE AMPE MAU DIEWE MAJIKAN AMPE HAMIL ABIS ITU DIPECAT LAGI TOLOL MENDING LU URUS BAPAKLU YANG KENA STROKE JANTUNGAN JADI PENYAKIT KOMPLIKASI BEGITU GARA GARA NGELIAT MAK LU YANG BEJAT BAT KELAKUAN NYA NOH BAPAKLU UDAH BAU BAT BAU KASURNYA BOKER KENCING SEMBARANGAN BAU BAU IN TETANGGA TOLOL MANA DIUSIR DARI DAERAH SITU NAJIS BAT SIH HIDUP LU MANA HIDUP NUMPANG DIEMPERAN RUKO MAKAN MINTA MINTA KALO GA KOREK KOREK TONG SAMPAH KALO GADAPET MAKAN DAUN UDAH KEK KAMBING AJA TOLOL UDAH BULU TEBEL DEKIL BAU LAGI KONTOL DIDIK DULU NOH ADEKLU BIAR GA JADI LACUR KEK MAK LU MANA MASIH KECIL SUKA BAT NYEPONGIN KONTOL TETANGGA CUMA PEN DAPET DUIT JAJAN KARENA HIDUP KELUARGALU TERLALU MISKIN KASIAN BAT SIH MENDING LU JADI ANAK BERGUNA DIKIT TOLOL MANA JADI BEBAN HOBI BAT SIH MABOK MABOKAN MANA MABOK KOMIK UDAH HASIL NYOLONG DARI RUKO ORANG DIH KERJAAN NGAMEN DILAMPU MERAH HABIS ITU BEGAYA PASANG TOGEL CUMA GOCENG BERHARAP BAT DAPET HASIL BUAT NYAMBUNG HIDUPLU YANG GA BERGUNA ITU DIH MAKANYA YA JADI ANAK HARAM JAN KEBANYAKAN TINGKAH KONTOL**"
    )


CMD_HELP.update(
    {
        "war2": "**Modules** - `war2`\
        \n\n Cmd : `.gigolo`\
        \nUsage : coba aja sendiri\
        \n\n Cmd : `.ngerocos`\
        \nUsage : coba aja sendiri\
        \n\n Cmd : `.kake`\
        \nUsage : coba aja sendiri\
        \n\n Cmd : `.badut`\
        \nUsage : coba aja sendiri\
        \n\n Cmd : `.mesum`\
        \nUsage : coba aja sendiri\
        \n\n Cmd : `.petinggi`\
        \nUsage : coba aja sendiri\
        \n\n Cmd : `.blepotan`\
        \nUsage : coba aja sendiri\
        \n\n Cmd : `.kudanil`\
        \nUsage : coba aja sendiri\
        \n\n Cmd : `.ovt`\
        \nUsage : ngeledek orang ovt\
    "
    }
)
